import { eslintConfig } from "@bluzzi/eslint-config";

export default eslintConfig(
  {
    typescript: { tsconfigPath: "./tsconfig.json" },
  },
  {
    ignores: ["src/react/ui", "src/react/hooks/use-mobile.ts", "next-env.d.ts"], // File generated by shadcn/ui
  },
  {
    rules: {
      "@eslint-react/hooks-extra/no-direct-set-state-in-use-effect": "off",
      "react-hooks/exhaustive-deps": "off",
    },
  },
);
